//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagmentSystem2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int IdAppointment { get; set; }
        public string IdPatient { get; set; }
        public string IdDoctor { get; set; }
        public string Date { get; set; }
        public string Medicine { get; set; }
        public string Samples { get; set; }
        public string SamplesResults { get; set; }
        public string Imaging { get; set; }
        public string ImagingResults { get; set; }
        public string Diagnoses { get; set; }
        public byte state { get; set; }
    }
}
