//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagmentSystem2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageAppointment
    {
        public Nullable<int> ImageID { get; set; }
        public int AppointmentID { get; set; }
        public Nullable<int> Ni { get; set; }
        public Nullable<int> Cr { get; set; }
        public Nullable<int> Mo { get; set; }
        public Nullable<int> Al { get; set; }
        public Nullable<int> Ti { get; set; }
        public Nullable<int> Nb { get; set; }
    }
}
