//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagmentSystem2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleAppointment
    {
        public Nullable<int> SampleID { get; set; }
        public int AppointmentID { get; set; }
        public string PlainSerum { get; set; }
        public string EDTAplasma { get; set; }
        public string EDTAwholeblood { get; set; }
        public string AllBloodSamples { get; set; }
    }
}
